# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a845d345f0cd1ab8de053c6a885a380e0f582b3b0288f04a7b63d0acc0fead334f9e379295cf2471eae98c6dd62f56bf3b55b2b52823917f14d79118f2b0709b
  FGLOGIN_MANDRILL_USERNAME: oakteam10102@gmail.com
  FGLOGIN_MANDRILL_APIKEY: zSLbjGrUdJHrEZKX8NLbfw

test:
  secret_key_base: de0f6b144ee75f9a39df28b7e43083e04b4eb754abf2923254ef40758ac7d496fd66f6f524336bdf33be835798db035f7e7f825608c29735ce2041909b8c0a53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FGLOGIN_MANDRILL_USERNAME: oakteam10102@gmail.com
  FGLOGIN_MANDRILL_APIKEY: zSLbjGrUdJHrEZKX8NLbfw